all:
	gcc ext2_cp.c helper.c -o ext2_cp -w
	gcc ext2_mkdir.c helper.c -o ext2_mkdir -w
	gcc ext2_ln.c helper.c -o ext2_ln -w
	gcc ext2_rm.c helper.c -o ext2_rm -w
	gcc ext2_restore.c helper.c -o ext2_restore -w
	gcc ext2_checker.c helper.c -o ext2_checker -w 